- id: autocopyright
  name: autocopyright
  description: "Adds missing copyright headers to source files."
  entry: autocopyright
  args: [-i]
  language: python
  types: [python]
  always_run: true
  pass_filenames: false
